version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
#      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket th-dest1
#                                   --output-template-file NewSamTemplate.yaml
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - /bin/pwd
      - /bin/ls -l
artifacts:
  type: zip
  files: 
  - '**/*'
  discard_paths: yes
